### ISSUE TITLE
Entire world is invisible

### ISSUE THREAD

**Issue by WrennWhitlock** [LO6AN/New-Frontier-Craft#99]
No matter what the settings are the world is visually gone.

![2023-02-02_10 04 48](https://user-images.githubusercontent.com/65571427/216377919-582e5110-cc21-4217-86f6-c7327351d015.png)

P.S. sorry for the bad Issue report I've never done this before

**Comment by forkiesassds** [comment]
Known issue, for the time being install the AMD patch to fix this issue. It should be fixed in NFC 3.5

**Comment by VivianTheFox** [comment]
Tentatively marking this as closed as I believe I fixed the bug in v3.4.2_02

**Comment by VivianTheFox** [comment]
Reopening it, it's still occurring on some machines, just much less frequently
